### ISSUE TITLE
attack did not success, I do not know the reason

### ISSUE THREAD

**Issue by liubiliubi** [LostOxygen/poison_froggo#3]
Hello, dear author. I'm in some trouble. I tried to change the dataset dog to a traffic sign with a speed limit of 30 and fish to a traffic sign with a speed limit of 100
![20ce977a4bf4bfb49865472dd1d9328](https://github.com/LostOxygen/poison_froggo/assets/145520617/5d4614f9-5d2b-429b-b7a1-3eaa13705547)

I only changed this part of the code because of the library version
![4be0481ebeba1662a69408ec136f66e](https://github.com/LostOxygen/poison_froggo/assets/145520617/6d70f8c7-992c-429b-a9f3-d6a938acc32a)

I changed EPOCHS = 100 to EPOCHS = 15 to save time, but it still took me 4 hours to run code.

These are the only three changes I made to the code.

I don't understand why the result is like the picture below
Why didn't the attack succeed
![2e4cc665904ef8db34d29c169d3cf86](https://github.com/LostOxygen/poison_froggo/assets/145520617/1109d6d1-59b1-4f65-a7f7-592098e8a834)
![d1db8c477d4ef37c9b4a08bb340c948](https://github.com/LostOxygen/poison_froggo/assets/145520617/fb2fcb35-4edc-4ec5-9d3a-5c78eff6fa73)

Hope to get your reply, thank you！

**Comment by LostOxygen** [comment]
I'm sorry, i'm not sure why you have these problems.
The images get resized to 299x299 pixels, so if your images are bigger it will cause the code to have a lot of processing overhead which could explain the longer training time.
For the attack: maybe you could try increasing the perturbation strength.
